# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Geo-ShapeFile
version:      2.51
version_from: ShapeFile.pm
installdirs:  site
requires:
    Carp:                          0
    IO::File:                      0
    Math::Trig:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
