--- #YAML:1.0
name:                Geo-ShapeFile
version:             2.52
abstract:            Perl extension for handling ESRI GIS Shapefiles.
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Carp:                          0
    IO::File:                      0
    Math::Trig:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Jason Kohles <email@jasonkohles.com>
