---
abstract: 'Perl extension for handling ESRI GIS Shapefiles.'
author:
  - 'Shawn Laffan <shawnlaffan@gmail.com>'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.132830'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Geo-ShapeFile
no_index:
  directory:
    - t
    - inc
resources:
  repository: https://github.com/shawnlaffan/Geo-ShapeFile.git
version: 2.57_001
